### PR TITLE
[merged] fix(kallsyms): Correct text address value

### PR DESCRIPTION
**Pull request by jmcadden**
Renamed /misc/kallsyms to /misc/ebbrt.kallsyms
Fixed cmdline flag: nodns -> nodhcp

### CODE REVIEW

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 7bbcdeb has been approved by `jmcadden`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 7bbcdeb with merge ba56eb3...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/190)
Approved by: jmcadden
Pushing ba56eb372d31926e6b69156d9213002a17f7af15 to master...

**Pull request closed without merging**
