### PR TITLE
[merged] feat(utils) added ability to unconditionally cleanup

### PR DESCRIPTION
**Pull request by jappavoo**
if you pass an argument to contrib/clean_running_apps.sh
then it will skip the prompt and do the cleanup unconditionally

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: db6cd90978ff7d5b5806816cdf12fb5a0ea22842
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/SESA/EbbRT/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by jappavoo** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit db6cd90 has been approved by `jappavoo`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit db6cd90 with merge 5fbb682...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/174)
Approved by: jappavoo
Pushing 5fbb682b831c8b1d6b5ed5c68f607c9c21a5cf4c to master...

**Pull request closed without merging**
