### PR TITLE
[merged] fix(Gthread): Block on recursive mutex lock

### PR DESCRIPTION
**Pull request by jmcadden**

### CODE REVIEW

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit a094615 has been approved by `jmcadden`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit a094615 with merge 9684daf...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/158)
Approved by: jmcadden
Pushing 9684daf8d48f8f3f729f49d9087cfed2292b5b22 to master...

**Pull request closed without merging**
