### PR TITLE
[merged] fix(build): Remove pkgconfig for capnp

### PR DESCRIPTION
**Pull request by dschatzberg**
Ensure that we don't check with pkgconfig to find capnp

### CODE REVIEW

**Comment by handong32** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit be62af3 has been approved by `handong32`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit be62af3 with merge 0f7ca34...

**Comment by BetsyRT** [comment]
:broken_heart: Test failed - [runtests](http://192.168.73.2:8010/builders/runtests/builds/101)

**Comment by dschatzberg** [comment]
@BetsyRT retry

**Comment by BetsyRT** [comment]
:hourglass: Testing commit be62af3 with merge 10b0c99...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/103)
Approved by: handong32
Pushing 10b0c9908d0cf6e3bbfb762e9a970f794e78bcfd to master...

**Pull request closed without merging**
