### PR TITLE
gcc5.3 compatibility changes

### PR DESCRIPTION
**Pull request by jmcadden**
Fixes required to build with gcc 5.3

### CODE REVIEW

**Comment by jmcadden** [comment]
Only hello-world has been tested with the new toolchain

**Comment by dschatzberg** [comment]
What is the issue with atomic and volatile? I reasoned to myself that we needed both when I originally wrote that code.

The try { } catch in the GP allocator is really no good. We can't afford to be throwing exceptions on allocations. I'm assuming the issue is that `size_t` is unsigned. Can we use `ssize_t` instead of `size_t`?

**Comment by jmcadden** [comment]
See the commit msg body for a pointer to the atomic volatile issue. In
short, atomic can no longer be defined as volatile as of gcc5. I believe
the c++ standard says atomic volatiles are implementation specific.

Ssize_t should work, but would require changing the type through the
allocators, which may require changes to the code interacting with it.
Seems like the correct way forward.

I'm curious, the case the Indexer throws an exception seems rare, and it is
caught directly after the operation. Is this really going to cost much?

**Comment by dschatzberg** [comment]
I suppose the fix for atomic<volatile foo> is to turn it into volatile atomic<foo>. Volatility is still important because this is talking to "hardware."

The indexing out of bounds case is not necessarily all that rare - any allocation larger than what the page allocator supports will hit that case. Actually throwing and catching exceptions is a fairly significant overhead, probably on the order of 100 nanoseconds. It also causes some code bloat (in the actual binary) to provide the unwinding landing pad.

The `ssize_t` fix should be local to the gp allocator, the `operator()` on the `Indexer` just needs to return `ssize_t` instead of `size_t`. Then the `ssize_t` can be used to index into the array once we check that it is `>= 0`. Note that this doesn't change the interface to anything (including the `Indexer`)

**Comment by dschatzberg** [comment]
Closing this in favor of #98

**Pull request closed without merging**
