### PR TITLE
[merged] fix(Dockerfile): NIC queues equal to cores count

### PR DESCRIPTION
**Pull request by jmcadden**
Remove environment variable option to set NIC queues

### CODE REVIEW

**Comment by bucs210** [comment]
@BetsyRT r+

**Comment by handong32** [comment]
@BetsyRT r+

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by jmcadden** [comment]
@dschatzberg Betsy appears to be out sick. Would you take a look, or give pointer?

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by jmcadden** [comment]
@dschatzberg  Hmm.. Betsy is still being silent while the homu container is running. Anything we're missing?

```
jmcadden@bd-sesa2:~ $ sudo docker ps
CONTAINER ID        IMAGE               COMMAND              CREATED             STATUS              PORTS                      NAMES
8bec3cb4137f        homu                "/usr/bin/homu -v"   17 hours ago        Up 17 hours         0.0.0.0:54856->54856/tcp   homu
```

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 27c4858 has been approved by `jmcadden`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 27c4858 with merge 09d867f...

**Comment by BetsyRT** [comment]
:broken_heart: Test failed - [runtests](http://192.168.73.2:8010/builders/runtests/builds/106)

**Comment by jmcadden** [comment]
@BetsyRT retry

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 27c4858 with merge a84a2a1...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/107)
Approved by: jmcadden
Pushing a84a2a18105080bbbaadc530587fd6851011cb55 to master...

**Pull request closed without merging**
