### PR TITLE
Polymorphic GlobalIdMap with ZooKeeper implementation 

### PR DESCRIPTION
**Pull request by jmcadden**
Add a GlobalIdMap implementation using the ZooKeeper Ebb.  

This PR contains the following features and fixes required to make the above functional:

- Polymorphic "GlobalIdMapBase"
- Support for multi-inheritance types in the Messageable template
- constexpr hash(string) method for generating deterministic static global EbbIds
- correct znode argument passing in ZooKeeper

### CODE REVIEW

**Comment by BetsyRT** [comment]
:umbrella: The latest upstream changes (presumably 0e086f2) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by BetsyRT** [comment]
:umbrella: The latest upstream changes (presumably 1b2f4b8) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by BetsyRT** [comment]
:umbrella: The latest upstream changes (presumably 922be49) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by jmcadden** [comment]
@BetsyRT try

**Comment by BetsyRT** [comment]
:hourglass: Trying commit f8e6dcc with merge 7f8e140...

**Comment by BetsyRT** [comment]
:broken_heart: Test failed - [runtests](http://192.168.73.2:8010/builders/runtests/builds/192)

**Comment by jmcadden** [comment]
@BetsyRT try

**Comment by jmcadden** [comment]
@BetsyRT clean

**Comment by jmcadden** [comment]
@BetsyRT retry

**Comment by BetsyRT** [comment]
:hourglass: Trying commit f8e6dcc with merge cde4db0...

**Comment by BetsyRT** [comment]
:broken_heart: Test failed - [runtests](http://192.168.73.2:8010/builders/runtests/builds/194)

**Comment by jmcadden** [comment]
@BetsyRT try

**Comment by BetsyRT** [comment]
:hourglass: Trying commit 17f9faf with merge e010dfa...

**Comment by BetsyRT** [comment]
:broken_heart: Test failed - [runtests](http://192.168.73.2:8010/builders/runtests/builds/196)

**Comment by jmcadden** [comment]
@BetsyRT retry

**Comment by BetsyRT** [comment]
:hourglass: Trying commit 17f9faf with merge b8abbaf...

**Comment by BetsyRT** [comment]
:broken_heart: Test failed - [runtests](http://192.168.73.2:8010/builders/runtests/builds/198)

**Comment by jmcadden** [comment]
@BetsyRT retry

**Comment by BetsyRT** [comment]
:hourglass: Trying commit 17f9faf with merge 6377345...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/200)
State: approved= try=True

**Pull request merged**
