### PR TITLE
Build param

### PR DESCRIPTION
**Pull request by handong32**

### CODE REVIEW

**Comment by handong32** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit f36f468 has been approved by `handong32`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit f36f468 with merge 3f644f5...

**Comment by BetsyRT** [comment]
:broken_heart: Test failed - [runtests](http://192.168.73.2:8010/builders/runtests/builds/133)

**Pull request closed without merging**
