### PR TITLE
[merged] feat(apps): Add node.js application

### PR DESCRIPTION
**Pull request by dschatzberg**

### CODE REVIEW

**Comment by handong32** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 9772063 has been approved by `handong32`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 9772063 with merge 684c753...

**Comment by BetsyRT** [comment]
:broken_heart: Test failed - [runtests](http://192.168.73.2:8010/builders/runtests/builds/102)

**Comment by dschatzberg** [comment]
@BetsyRT retry

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 9772063 with merge 18c7063...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/104)
Approved by: handong32
Pushing 18c70639db3a1cc9b8ab9083471811c392418d08 to master...

**Pull request closed without merging**
