### PR TITLE
[merged] Restructure source directory

### PR DESCRIPTION
**Pull request by jmcadden**

### CODE REVIEW

**Comment by dschatzberg** [comment]
Excellent, looks just like what we discussed. If you have a second, there is at least some dead code (Buffer.cc is completely commented out). It would be nice to just go through and nuke what we don't need. @BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit b0d3324 has been approved by `dschatzberg`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit b0d3324 with merge 02440e9...

**Comment by BetsyRT** [comment]
:broken_heart: Test failed - [runtests](http://192.168.73.2:8010/builders/runtests/builds/117)

**Comment by jmcadden** [comment]
First attempt using an updated buildbot master script. @BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 546db24 has been approved by `jmcadden`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 546db24 with merge ef20783...

**Comment by BetsyRT** [comment]
:broken_heart: Test failed - [runtests](http://192.168.73.2:8010/builders/runtests/builds/119)

**Comment by jmcadden** [comment]
squashed all commits into one. @BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 1e2fe44 has been approved by `jmcadden`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 1e2fe44 with merge f8c9e56...

**Comment by BetsyRT** [comment]
:broken_heart: Test failed - [runtests](http://192.168.73.2:8010/builders/runtests/builds/120)

**Comment by jmcadden** [comment]
failure due to stale state on buildbotslave. @BetsyRT retry

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 1e2fe44 with merge 04a08c3...

**Comment by BetsyRT** [comment]
:broken_heart: Test failed - [runtests](http://192.168.73.2:8010/builders/runtests/builds/121)

**Comment by jmcadden** [comment]
Second attempt using updated build. @BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 3aa1046 has been approved by `jmcadden`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 3aa1046 with merge e5fe803...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/122)
Approved by: jmcadden
Pushing e5fe8030d85a6b179f4ab2791d6e82e75d0b14c2 to master...

**Pull request closed without merging**
