### PR TITLE
fix(build): cmake no longer search host for capnp

### PR DESCRIPTION
**Pull request by jmcadden**

### CODE REVIEW

**Comment by dschatzberg** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit a250b88 has been approved by `dschatzberg`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit a250b88 with merge dcfd810...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/91)
Approved by=dschatzberg
Pushing dcfd810a3c30f6265aa52430de67a706584fc8a3 to master...

**Pull request merged**
