### PR TITLE
[merged] Added an explicit target for generating ebbrt native makefile

### PR DESCRIPTION
**Pull request by jappavoo**
Added an extra phony target to explicitly create native build makefile.

This is useful for external users of ebbrt that want to do fast builds that avoids
having a tool chain build (e.g. only have an install of the tool chain).  More specifically 
it does not check dependencies on the tool chain or directories.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 863d668a733f467d2878d63ff2b3fb08cea5738b
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/SESA/EbbRT/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 7199de7b9573e612af5c1ee645dec38d42bfceaa
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/SESA/EbbRT/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by tommy-u** [comment]
@BetsyRT r+

**Comment by handong32** [comment]
@BetsyRT retry

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 4d0d429 has been approved by `jmcadden`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 4d0d429 with merge 878d7c8...

**Comment by BetsyRT** [comment]
:broken_heart: Test failed - [runtests](http://192.168.73.2:8010/builders/runtests/builds/168)

**Comment by jmcadden** [comment]
@BetsyRT retry

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 4d0d429 with merge 0cd6034...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/169)
Approved by: jmcadden
Pushing 0cd603492e0838cd30a11784becc81fc2d18b616 to master...

**Pull request closed without merging**
