### PR TITLE
refactor(helloworld): Update CMakeLists.txt

### PR DESCRIPTION
**Pull request by dschatzberg**

### CODE REVIEW

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 059b542 has been approved by `jmcadden`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 059b542 with merge 47863cd...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/92)
Approved by=jmcadden
Pushing 47863cdd515b0e20b73c71b782470417daae3c86 to master...

**Pull request merged**
