### PR TITLE
feat(lib): add boost::expected

### PR DESCRIPTION
**Pull request by dschatzberg**

### CODE REVIEW

**Comment by dschatzberg** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit a1bc924 has been approved by `dschatzberg`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit a1bc924 with merge 66ede7f...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/22)
Approved by=dschatzberg
Pushing 66ede7fec6c8121b5fb99625691766726f97ebee to master...

**Pull request merged**
