### PR TITLE
Fix recursive lock and config in Filesystem library

### PR DESCRIPTION
**Pull request by dschatzberg**

### CODE REVIEW

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 88f5d5d has been approved by `jmcadden`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 88f5d5d with merge 7ef286b...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/94)
Approved by=jmcadden
Pushing 7ef286bd920f5a27bc92ca349e4087c25777e6a7 to master...

**Pull request merged**
