### PR TITLE
feat(Perf): Intel Performance Counter Monitor

### PR DESCRIPTION
**Pull request by jmcadden**
PerfCounter object is bound to a hardware counter and event-type. Each
counter is core local and there is no concurrency when add/removing
counter objects.

### CODE REVIEW

**Comment by dschatzberg** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 22a58ce has been approved by `dschatzberg`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 22a58ce with merge fc26789...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/7)
Approved by=dschatzberg
Pushing fc267898344b28f44b127798fbe8e7766ef3b59a to master...

**Pull request merged**
