### PR TITLE
Clean up the makefile/build

### PR DESCRIPTION
**Pull request by jmcadden**

### CODE REVIEW

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 061d1cb has been approved by `jmcadden`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 061d1cb with merge b760d0b...

**Comment by jmcadden** [comment]
@BetsyRT try

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:bulb: This pull request was already approved, no need to approve it again.

- This pull request previously failed. You should add more commits to fix the bug, or use `retry` to trigger a build again.

**Comment by BetsyRT** [comment]
:pushpin: Commit 061d1cb has been approved by `jmcadden`

**Comment by jmcadden** [comment]
@BetsyRT retry

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 061d1cb with merge 195b2ee...

**Comment by BetsyRT** [comment]
:broken_heart: Test failed - [runtests](http://10.241.31.7:8010/builders/runtests/builds/175)

**Pull request closed without merging**
