### PR TITLE
Remove FDT header

### PR DESCRIPTION
**Pull request by dschatzberg**

### CODE REVIEW

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 42c8410 has been approved by `jmcadden`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 42c8410 with merge 37e099e...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/93)
Approved by=jmcadden
Pushing 37e099ef61b075a5a6f5597daa10c64c9adbcd65 to master...

**Pull request merged**
