### PR TITLE
[merged] Socket api

### PR DESCRIPTION
**Pull request by jmcadden**
Adds basic socket interface library

### CODE REVIEW

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 1d7d6c5 has been approved by `jmcadden`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 1d7d6c5 with merge b98e4b0...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/141)
Approved by: jmcadden
Pushing b98e4b087d989ca00ffe7fc839ae86bbd2359bf3 to master...

**Pull request closed without merging**
