### PR TITLE
[merged] feat(Future): block on Future<void>

### PR DESCRIPTION
**Pull request by jmcadden**
Add implementation of Future<void>::Block() and SharedFuture<void>::Block().

### CODE REVIEW

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 7d201da has been approved by `jmcadden`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 7d201da with merge 19794b6...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/127)
Approved by: jmcadden
Pushing 19794b699841e205f5366b598d8d866b5531bfe7 to master...

**Pull request closed without merging**
