### PR TITLE
[merged] feat(NetworkManager): Add internal lo interface

### PR DESCRIPTION
**Pull request by jmcadden**
Routes IP traffic on the range of "link-local" address (169.254.x.x) 

https://en.wikipedia.org/wiki/Link-local_address

### CODE REVIEW

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 7eb5b9e has been approved by `jmcadden`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 7eb5b9e with merge 889cdf3...

**Comment by jmcadden** [comment]
@BetsyRT retry

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 7eb5b9e with merge d213abd...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://10.241.31.7:8010/builders/runtests/builds/14)
Approved by: jmcadden
Pushing d213abd76f3cc065755170876cc269d97591abd3 to master...

**Pull request closed without merging**
