### PR TITLE
[merged] feat(startup): static ebb ClassInit

### PR DESCRIPTION
**Pull request by jappavoo**
New protocol to allow static Ebbs to add logic
to the Init call provided by the template classes.
Specifically you must provide a ClassInit that will
be from within the provided Init call.  You may of
course provide an empty body.

Used this feature to fix the NodeAllocator initialization
bug.  NodeAllocator now provides a ClassInit that sets up
the global defaults.  This ensures that they are ready
when any call to the NodeAllocator is made including the
first call which may trigger a Ebb miss (which only then
creates the first rep).

Closes: #213

### CODE REVIEW

**Comment by jappavoo** [comment]
As part of this commit I have removed Javier and Stephanie's work arounds to the NodeAllocator.  They put these in place to avoid the race condition between the first rep being created and the defaults not being set yet.

**Comment by jappavoo** [comment]
@BetsyRT r+

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit ce2f756 has been approved by `jmcadden`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit ce2f756 with merge 1b2f4b8...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/172)
Approved by: jmcadden
Pushing 1b2f4b867d010157fe9c47d7ab31f15b7c7d1e76 to master...

**Pull request closed without merging**
