### PR TITLE
chore(build): Major cleanup of Makefiles 

### PR DESCRIPTION
**Pull request by jmcadden**
Major cleanup to the root makefile

### CODE REVIEW

**Comment by jmcadden** [comment]
@BetsyRT try

**Comment by BetsyRT** [comment]
:hourglass: Trying commit cfb7522 with merge b470933...

**Comment by BetsyRT** [comment]
:broken_heart: Test failed - [runtests](http://10.241.31.7:8010/builders/runtests/builds/176)

**Comment by jmcadden** [comment]
@BetsyRT retry

**Comment by BetsyRT** [comment]
:hourglass: Trying commit cfb7522 with merge 799ae6e...

**Comment by BetsyRT** [comment]
:broken_heart: Test failed - [runtests](http://10.241.31.7:8010/builders/runtests/builds/177)

**Comment by jmcadden** [comment]
@BetsyRT retry

**Comment by BetsyRT** [comment]
:hourglass: Trying commit cfb7522 with merge 4fc16ec...

**Comment by jmcadden** [comment]
@BetsyRT retry

**Comment by BetsyRT** [comment]
:hourglass: Trying commit cfb7522 with merge 163299c...

**Comment by BetsyRT** [comment]
:broken_heart: Test failed - [runtests](http://10.241.31.7:8010/builders/runtests/builds/1)

**Comment by jmcadden** [comment]
@BetsyRT retry

**Comment by BetsyRT** [comment]
:hourglass: Trying commit cfb7522 with merge 557e31e...

**Comment by jmcadden** [comment]
@BetsyRT retry

**Comment by jmcadden** [comment]
@BetsyRT retry

**Comment by jmcadden** [comment]
@BetsyRT try

**Comment by BetsyRT** [comment]
:hourglass: Trying commit cfb7522 with merge 7948713...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://10.241.31.7:8010/builders/runtests/builds/3)
State: approved= try=True

**Pull request merged**
