### PR TITLE
Smp/Fpu fix: Set fpu precision to 64bit

### PR DESCRIPTION
**Pull request by jmcadden**
FPU on secondary cores was not being initialized correctly, and was defaulting to 24-bit (single precision).

### CODE REVIEW

**Comment by awadyn** [comment]
@BetsyRT try

**Comment by jmcadden** [comment]
@BetsyRT try

**Comment by awadyn** [comment]
@BetsyRT try

**Comment by jmcadden** [comment]
@BetsyRT try

**Comment by BetsyRT** [comment]
:hourglass: Trying commit 620da78 with merge b609bc9...

**Comment by BetsyRT** [comment]
:broken_heart: Test failed - [runtests](http://192.168.73.2:8010/builders/runtests/builds/167)

**Comment by awadyn** [comment]
@BetsyRT retry

**Comment by BetsyRT** [comment]
:hourglass: Trying commit 620da78 with merge 0e39c0e...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/169)
State: approved= try=True

**Pull request merged**
