### PR TITLE
[merged] fix(Hosted): Check for AppMain before invoking

### PR DESCRIPTION
**Pull request by jmcadden**

### CODE REVIEW

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 33eebbf has been approved by `jmcadden`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 33eebbf with merge 856c84c...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/153)
Approved by: jmcadden
Pushing 856c84c53018ca91eb2c8d7d6bd13bb76e07e131 to master...

**Pull request closed without merging**
