### PR TITLE
[merged] NodeAllocator configuration options

### PR DESCRIPTION
**Pull request by jmcadden**
Set the node allocator network specification via environment variables 

Also, removes debug Dockerfile

- [x] Needs testing with Docker Swarm + Weave

### CODE REVIEW

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit b46d8cf has been approved by `jmcadden`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit b46d8cf with merge d951f55...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/145)
Approved by: jmcadden
Pushing d951f55f11f7a274eb9e96529181a98da48461c0 to master...

**Pull request closed without merging**
