### PR TITLE
[merged] feat(PoolAllocator): add PoolAllocator

### PR DESCRIPTION
**Pull request by jmcadden**
Add an abstraction for creating a Pool of nodes, along with a helloworld-pool app that uses the pool allocator 

This is a re-post of PR #210 with merge conflicts resolved and condensed into a single commit

### CODE REVIEW

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit d8a1389 has been approved by `jmcadden`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit d8a1389 with merge 121db01...

**Comment by BetsyRT** [comment]
:broken_heart: Test failed - [runtests](http://192.168.73.2:8010/builders/runtests/builds/175)

**Comment by jmcadden** [comment]
@BetsyRT retry

**Comment by BetsyRT** [comment]
:hourglass: Testing commit d8a1389 with merge 2c889d6...

**Comment by BetsyRT** [comment]
:broken_heart: Test failed - [runtests](http://192.168.73.2:8010/builders/runtests/builds/176)

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit e8073a4 has been approved by `jmcadden`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit e8073a4 with merge b82f2ac...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/177)
Approved by: jmcadden
Pushing b82f2ace3ccfbe00d066a7d2bd2bd506a3701d25 to master...

**Pull request closed without merging**
