### PR TITLE
fix(net): zero out memory

### PR DESCRIPTION
**Pull request by handong32**
need to pass in True to MakeUniqueIOBuf to ensure memory
allocated for DHCP packets are zero'd out and not filled
with garbage

### CODE REVIEW

**Comment by dschatzberg** [comment]
@EbbRT-Homu r+

**Comment by EbbRT-Homu** [comment]
:pushpin: Commit 7896111 has been approved by `dschatzberg`

**Comment by EbbRT-Homu** [comment]
:hourglass: Testing commit 7896111 with merge 9b46cfc...

**Comment by EbbRT-Homu** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/9)
Approved by=dschatzberg
Pushing 9b46cfcde749fd0d14bcb8276f0754586dbf8535 to master...

**Pull request merged**
