### PR TITLE
[merged] Update node

### PR DESCRIPTION
**Pull request by handong32**

### CODE REVIEW

**Comment by jmcadden** [comment]
While these changes are right, we probably don't want per-library build instructions unless there's something unusual about it. Instead we should have a general "Building w/ Ebb Libraries" instructions which live in our top-level README or as a file in the /docs directory.

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit ede9715 has been approved by `jmcadden`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit ede9715 with merge e7125f7...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/125)
Approved by: jmcadden
Pushing e7125f734be2606b2d1298921309cca48ebb7044 to master...

**Pull request closed without merging**
