### PR TITLE
[merged] fix(NodeAllocator): Add netcat test to allocation

### PR DESCRIPTION
**Pull request by jmcadden**
netcat added as reliable way to check that the container is up and able to receive the backend image (via scp).

### CODE REVIEW

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 66a2e19 has been approved by `jmcadden`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 66a2e19 with merge aa5a28c...

**Comment by BetsyRT** [comment]
:broken_heart: Test failed - [runtests](http://192.168.73.2:8010/builders/runtests/builds/136)

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit df47dc1 has been approved by `jmcadden`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit df47dc1 with merge c922707...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/138)
Approved by: jmcadden
Pushing c922707e02495a654131b27ff69f01ad002d0209 to master...

**Pull request closed without merging**
