### PR TITLE
feat(EbbRef): casting EbbRefs of convertible types

### PR DESCRIPTION
**Pull request by jmcadden**
EbbRefs of convertible types can be cast both implicitly and explicitly.

### CODE REVIEW

**Comment by dschatzberg** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 6c1305e has been approved by `dschatzberg`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 6c1305e with merge 0caa25e...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/20)
Approved by=dschatzberg
Pushing 0caa25e8f80a1f3291f34a6493f4ffa3b543235d to master...

**Pull request merged**
