### PR TITLE
fix(Dockerfile): multiqueue setup for single-core

### PR DESCRIPTION
**Pull request by jmcadden**
Correctly sets the multiqueue network interface when allocating a single-core VM (previously QEMU would spit in error)

### CODE REVIEW

**Comment by dschatzberg** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 6edf64d has been approved by `dschatzberg`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 6edf64d with merge b13ddda...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/50)
Approved by=dschatzberg
Pushing b13dddaf737be943971ac0eb1fe9598e2c47568f to master...

**Pull request merged**
