### PR TITLE
docs(techreport): Update link

### PR DESCRIPTION
**Pull request by dschatzberg**
Point to our official tech report PDF

### CODE REVIEW

**Comment by dschatzberg** [comment]
@EbbRT-Homu r+

**Comment by EbbRT-Homu** [comment]
:pushpin: Commit f634554 has been approved by `dschatzberg`

**Comment by EbbRT-Homu** [comment]
:hourglass: Testing commit f634554 with merge 439d1bd...

**Comment by EbbRT-Homu** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/5)
Approved by=dschatzberg
Pushing 439d1bd926ae497fcd4743e57a7f81080b2cc5f3 to master...

**Pull request merged**
