### PR TITLE
test(app): Add helloworld test

### PR DESCRIPTION
**Pull request by dschatzberg**
Add pexpect script to check for success of a helloworld app run.

### CODE REVIEW

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 37cde5c has been approved by `jmcadden`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 37cde5c with merge 9daf7f7...

**Comment by BetsyRT** [comment]
:broken_heart: Test failed - [runtests](http://192.168.73.2:8010/builders/runtests/builds/8)

**Comment by dschatzberg** [comment]
@BetsyRT retry

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 37cde5c with merge faac9b7...

**Comment by BetsyRT** [comment]
:broken_heart: Test failed - [runtests](http://192.168.73.2:8010/builders/runtests/builds/9)

**Comment by dschatzberg** [comment]
@BetsyRT retry

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 37cde5c with merge 744b21a...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/10)
Approved by=jmcadden
Pushing 744b21a8a6c489ca8190547a9369194b9b12b359 to master...

**Pull request merged**
