### PR TITLE
[merged] feat(hosted): implement ebbrt::Cpu interface

### PR DESCRIPTION
**Pull request by jmcadden**
This works to unify the hosted and native `ebbrt::Cpu` interface, and simplifies the process of starting EbbRT in a Linux thread by abstracting away much of the bring-up requirements. 

To-do: 
- [ ] review process and implementation

### CODE REVIEW

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 21ec9dd has been approved by `jmcadden`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 21ec9dd with merge b258817...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/150)
Approved by: jmcadden
Pushing b2588172653c7b8a0083cdc70c4d83d14a00b77e to master...

**Pull request closed without merging**
