### PR TITLE
chore(ci): Ensure build-slave runs as root

### PR DESCRIPTION
**Pull request by dschatzberg**
Signed-off-by: Dan Schatzberg <schatzberg.dan@gmail.com>

### CODE REVIEW

**Comment by jmcadden** [comment]
+r

**Comment by BetsyRT** [comment]
:pushpin: Commit 3419448 has been approved by `jmcadden`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 3419448 with merge f91e4fa...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/40)
Approved by=jmcadden
Pushing f91e4fa70ac30b1c7b2d9ca0c05c9a541ef7f0be to master...

**Pull request merged**
