### PR TITLE
[merged] fix(hosted): removed debug printfs

### PR DESCRIPTION
**Pull request by jappavoo**
Some debug printfs leaked into my last commit.  This commit removes them.

### CODE REVIEW

**Comment by jappavoo** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 6a4b1a1 has been approved by `jappavoo`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 6a4b1a1 with merge c5a56c0...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/173)
Approved by: jappavoo
Pushing c5a56c05cfa97ddfc370239c38e9c03bc21fda0e to master...

**Pull request closed without merging**
