### PR TITLE
[merged] Han cmdline rdmd

### PR DESCRIPTION
**Pull request by handong32**

### CODE REVIEW

**Comment by handong32** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit f8d2787 has been approved by `handong32`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit f8d2787 with merge 34553b5...

**Comment by BetsyRT** [comment]
:broken_heart: Test failed - [runtests](http://192.168.73.2:8010/builders/runtests/builds/111)

**Comment by handong32** [comment]
@BetsyRT retry

**Comment by BetsyRT** [comment]
:hourglass: Testing commit f8d2787 with merge c2094de...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/113)
Approved by: handong32
Pushing c2094de53fedd6daebfcea37e6f3610c1a7f7d91 to master...

**Pull request closed without merging**
