### PR TITLE
feat(NetworkId): Add ToString for backend

### PR DESCRIPTION
**Pull request by yeungsl**

### CODE REVIEW

**Comment by jmcadden** [comment]
@BetsyRT  r+

**Comment by BetsyRT** [comment]
:pushpin: Commit e2d65e6 has been approved by `jmcadden`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit e2d65e6 with merge a65116c...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/41)
Approved by=jmcadden
Pushing a65116ccad912ba6f45058da7f7ee8fcd2070582 to master...

**Pull request merged**
