### PR TITLE
ZooKeeper Ebb library

### PR DESCRIPTION
**Pull request by jmcadden**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: f066717448103d95f4fd58da7521b8769e73d962
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/SESA/EbbRT/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by jmcadden** [comment]
@BetsyRT +r

**Comment by BetsyRT** [comment]
:pushpin: Commit d4b36ca has been approved by `jmcadden`

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:bulb: This pull request was already approved, no need to approve it again.

**Comment by BetsyRT** [comment]
:pushpin: Commit d4b36ca has been approved by `jmcadden`

**Comment by jmcadden** [comment]
closing to reopen

**Pull request closed without merging**
