### PR TITLE
Intel Performance Monitor Counters

### PR DESCRIPTION
**Pull request by jmcadden**
PerfCounter object is bound to a hardware counter and event-type. Each
counter is core local and there is no concurrency when add/removing
counter objects.

### CODE REVIEW

**Comment by jmcadden** [comment]
@BetsyRT try

**Comment by BetsyRT** [comment]
:hourglass: Trying commit 5a01fa3 with merge aa10b17...

**Comment by BetsyRT** [comment]
:broken_heart: Test failed - [runtests](http://192.168.73.2:8010/builders/runtests/builds/4)

**Comment by jmcadden** [comment]
@BetsyRT try

**Comment by BetsyRT** [comment]
:hourglass: Trying commit 39a38a2 with merge cbdeff9...

**Comment by BetsyRT** [comment]
:broken_heart: Test failed - [runtests](http://192.168.73.2:8010/builders/runtests/builds/5)

**Comment by dschatzberg** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 22a58ce has been approved by `dschatzberg`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 22a58ce with merge 6e6910f...

**Comment by jmcadden** [comment]
@BetsyRT try

**Comment by dschatzberg** [comment]
@BetsyRT clean

**Comment by dschatzberg** [comment]
@BetsyRT force

**Comment by BetsyRT** [comment]
:bomb: Buildbot returned an error: `Authorization failed`

**Pull request closed without merging**
