### PR TITLE
[merged] refactor(Clock): add millisecond clock sleep

### PR DESCRIPTION
**Pull request by handong32**
Added SleepMilli to Clock.cc

### CODE REVIEW

**Comment by handong32** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit d11bb96 has been approved by `handong32`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit d11bb96 with merge b464b53...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/183)
Approved by: handong32
Pushing b464b53a920cda52f3f0b020f4befb3fd27b80b2 to master...

**Pull request closed without merging**
