### PR TITLE
[merged] Enable hostless boot

### PR DESCRIPTION
**Pull request by jmcadden**
The only way to manually boot a native/backend node is to build the native EbbRT library with networking and distributed runtime disabled (i.e., it can not be done on a per-app basis). This patch lessons the checks for host-side configuration, and allows an app to boot without knowledge of a its host and/or networking configuration. Warning: the system will crash if you boot this way and attempt to access the network.

### CODE REVIEW

**Comment by jmcadden** [comment]
@BetsyRT try

**Comment by BetsyRT** [comment]
:hourglass: Trying commit 32541cb with merge e900175...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/185)
State: approved= try=True

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 1650a82 has been approved by `jmcadden`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 1650a82 with merge 922be49...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/189)
Approved by: jmcadden
Pushing 922be494655a5a96919ea163ccc50ad855323dc9 to master...

**Pull request closed without merging**
