### PR TITLE
chore(baremetal): Remove lwip headers

### PR DESCRIPTION
**Pull request by jmcadden**

### CODE REVIEW

**Comment by dschatzberg** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 48ea435 has been approved by `dschatzberg`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 48ea435 with merge aa866dc...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/19)
Approved by=dschatzberg
Pushing aa866dcf6188f7069b7320cad50b3336379259d1 to master...

**Pull request merged**
