### PR TITLE
style(all): Apply lint and reformat

### PR DESCRIPTION
**Pull request by dschatzberg**
This commit applies all lint and reformatting rules

### CODE REVIEW

**Comment by dschatzberg** [comment]
@EbbRT-Homu +r

**Comment by dschatzberg** [comment]
@EbbRT-Homu r+

**Comment by EbbRT-Homu** [comment]
:pushpin: Commit 408b66a has been approved by `dschatzberg`

**Comment by EbbRT-Homu** [comment]
:hourglass: Testing commit 408b66a with merge 2adfef3...

**Comment by EbbRT-Homu** [comment]
:broken_heart: Test failed - [runtests](http://192.168.73.2:8010/builders/runtests/builds/6)

**Comment by dschatzberg** [comment]
@EbbRT-Homu retry

**Comment by EbbRT-Homu** [comment]
:hourglass: Testing commit 408b66a with merge 30fd312...

**Comment by EbbRT-Homu** [comment]
:broken_heart: Test failed - [runtests](http://192.168.73.2:8010/builders/runtests/builds/7)

**Comment by dschatzberg** [comment]
@EbbRT-Homu retry

**Comment by EbbRT-Homu** [comment]
:hourglass: Testing commit 408b66a with merge 4dc41ce...

**Comment by EbbRT-Homu** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/8)
Approved by=dschatzberg
Pushing 4dc41ce50713cedf39aef615d3129e3d6081d12c to master...

**Pull request merged**
