### PR TITLE
feat(Build): adds app-specific CPP,CXX,C,AS flags

### PR DESCRIPTION
**Pull request by jmcadden**

### CODE REVIEW

**Comment by dschatzberg** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 9b1cf89 has been approved by `dschatzberg`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 9b1cf89 with merge b5244f8...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/18)
Approved by=dschatzberg
Pushing b5244f8f0b41e2514c2f311b9d45af4d30ecfca3 to master...

**Pull request merged**
