### PR TITLE
[merged] fix(apps/msgtst): Send multiple messages

### PR DESCRIPTION
**Pull request by jmcadden**
Expand the messenger test to send multiple messages.

### CODE REVIEW

**Comment by handong32** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 3c21f39 has been approved by `handong32`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 3c21f39 with merge 301b19a...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/161)
Approved by: handong32
Pushing 301b19a48f335bcfd1ccc12647aa998fc18c4624 to master...

**Pull request closed without merging**
