### PR TITLE
partial support for sockets API on native

### PR DESCRIPTION
**Pull request by jmcadden**
Contains socket api support required for EbbRT ZooKeeper library. Most interfaces/argument-options remain unimplemented.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 9e56e8bbd10fbd910f0d4dbdc80bb8a2c1d414f4
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 6c83add86d1f7c14a0f27a130f82b2d47e4ed0d3
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/SESA/EbbRT/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d1ff89795ebd4c741f8e70bf2a57123f79e0f286
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/SESA/EbbRT/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 6c83add has been approved by `jmcadden`

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 049f61d has been approved by `jmcadden`

**Comment by jmcadden** [comment]
Closing to re-open

**Pull request closed without merging**
