### PR TITLE
NodeAllocator NodeArgs specification

### PR DESCRIPTION
**Pull request by jmcadden**

### CODE REVIEW

**Comment by jmcadden** [comment]
@BetsyRT try

**Comment by BetsyRT** [comment]
:hourglass: Trying commit 841792b with merge 09d083b...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/187)
State: approved= try=True

**Comment by jmcadden** [comment]
@BetsyRT +r

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 841792b has been approved by `jmcadden`

**Pull request merged**
