### PR TITLE
[merged] fix(NodeAllocator): wait for node to initialize

### PR DESCRIPTION
**Pull request by jmcadden**
Wait for the node's network to be reachable before attempting to send over the back-end image

Timeout set at 30 seconds

### CODE REVIEW

**Comment by dschatzberg** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit bb26aaf has been approved by `dschatzberg`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit bb26aaf with merge c2b7af1...

**Comment by BetsyRT** [comment]
:broken_heart: Test failed - [runtests](http://192.168.73.2:8010/builders/runtests/builds/97)

**Comment by jmcadden** [comment]
failured: `sh: 1: ping: not found`

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit b0da0cb has been approved by `jmcadden`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit b0da0cb with merge f91ed27...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/98)
Approved by: jmcadden
Pushing f91ed27a517967c660f3ad8401867d67dfb6c390 to master...

**Pull request closed without merging**
