### PR TITLE
chore(ci): build environment Dockerfile

### PR DESCRIPTION
**Pull request by jmcadden**

### CODE REVIEW

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 37249a5 has been approved by `jmcadden`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 37249a5 with merge 3e88e1d...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/42)
Approved by=jmcadden
Pushing 3e88e1dea7d2dfdd391c2fb4bd700385663bc205 to master...

**Pull request merged**
