### PR TITLE
[merged] Zookeeper client Ebb

### PR DESCRIPTION
**Pull request by jmcadden**
Adds library for zookeeper client ebb

### CODE REVIEW

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 84da273 has been approved by `jmcadden`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 84da273 with merge 2325569...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/143)
Approved by: jmcadden
Pushing 232556937a796c7f46315ae3e294473760cebf06 to master...

**Pull request closed without merging**
