### PR TITLE
feat(NodeAllocator): docker replaces kittyhawk

### PR DESCRIPTION
**Pull request by jmcadden**
NodeAllocator calls directly to docker service running on the host to create networks and allocate backend nodes.

TODO:
- ~~Pull node's assigned IP address from docker~~ 
- ~~add Dockerfile~~ 
- ~~transfer image into container & signal start~~
- correct gdb port assignment

### CODE REVIEW

**Comment by dschatzberg** [comment]
Is this good to go?

**Comment by jmcadden** [comment]
@dschatzberg no, not yet, one remaining issue w/ gdb port assignment

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 77ab5c0432a6c7453c8e25cc6a9a8ef7ecd1b07a
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/SESA/EbbRT/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by dschatzberg** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 7111921 has been approved by `dschatzberg`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 7111921 with merge 50f4f6d...

**Comment by BetsyRT** [comment]
:broken_heart: Test failed - [runtests](http://192.168.73.2:8010/builders/runtests/builds/37)

**Comment by dschatzberg** [comment]
@BetsyRT retry

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 7111921 with merge 175e3aa...

**Comment by BetsyRT** [comment]
:broken_heart: Test failed - [runtests](http://192.168.73.2:8010/builders/runtests/builds/38)

**Comment by dschatzberg** [comment]
@BetsyRT retry

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 7111921 with merge 10a5b9e...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/39)
Approved by=dschatzberg
Pushing 10a5b9e58af42de8f6579f1acc94abd06683f5d7 to master...

**Pull request merged**
