### PR TITLE
[merged] docs(README): added README.md

### PR DESCRIPTION
**Pull request by handong32**
Instructions for building hosted and native 
version of filesystem library

### CODE REVIEW

**Comment by jmcadden** [comment]
commit msg should probably read: `docs(lib/filesystem): Added README`  

Also - did you commit the change to the Makefile?

**Comment by handong32** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 373bf83 has been approved by `handong32`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 373bf83 with merge 603e721...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/109)
Approved by: handong32
Pushing 603e721cfda18cd2eb43a56c5237cac2c89d1a05 to master...

**Pull request closed without merging**
