### PR TITLE
[merged] feat(appgen): Add native app template

### PR DESCRIPTION
**Pull request by jmcadden**

### CODE REVIEW

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 9b68644 has been approved by `jmcadden`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 9b68644 with merge 91b1301...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/171)
Approved by: jmcadden
Pushing 91b13012711b238502053dfdca71dc1178a9243f to master...

**Pull request closed without merging**
