### PR TITLE
refactor(PageAllocator): change bytes to touch from 4K to 1K

### PR DESCRIPTION
**Pull request by handong32**
be less aggressive about touching pages for stack allocation in #135

### CODE REVIEW

**Comment by dschatzberg** [comment]
why 1096 and not 1024?

**Comment by dschatzberg** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 555ae42 has been approved by `dschatzberg`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 555ae42 with merge fee3323...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/48)
Approved by=dschatzberg
Pushing fee332397862ef10c03a8b2b0c5c7deb5a795d22 to master...

**Pull request merged**
