### PR TITLE
[merged] Generate static EbbId from string

### PR DESCRIPTION
**Pull request by jmcadden**
Adds a method to generate a global user EbbId using a string input. This is intended for external libraries to declare their own static EbbIds with little risk of conflict.

### CODE REVIEW

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit b2bb275 has been approved by `jmcadden`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit b2bb275 with merge 8a3d86e...

**Comment by BetsyRT** [comment]
:broken_heart: Test failed - [runtests](http://192.168.73.2:8010/builders/runtests/builds/146)

**Comment by jmcadden** [comment]
@BetsyRT retry

**Comment by BetsyRT** [comment]
:hourglass: Testing commit b2bb275 with merge 36ed687...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/148)
Approved by: jmcadden
Pushing 36ed687f86f6f64a1b93d203b36746d1b2bc5f13 to master...

**Pull request closed without merging**
