### PR TITLE
fix(Gthread): Block when acquiring mutex lock

### PR DESCRIPTION
**Pull request by jmcadden**

### CODE REVIEW

**Comment by dschatzberg** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 379ecc4 has been approved by `dschatzberg`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 379ecc4 with merge e3c9408...

**Comment by BetsyRT** [comment]
:broken_heart: Test failed - [runtests](http://192.168.73.2:8010/builders/runtests/builds/156)

**Pull request closed without merging**
