### PR TITLE
[merged] NodeAllocator maintenance 

### PR DESCRIPTION
**Pull request by jmcadden**

### CODE REVIEW

**Comment by jmcadden** [comment]
@BetsyRT +r

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 653d93b has been approved by `jmcadden`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 653d93b with merge f44b384...

**Comment by BetsyRT** [comment]
:broken_heart: Test failed - [runtests](http://192.168.73.2:8010/builders/runtests/builds/129)

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 6c32c72 has been approved by `jmcadden`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 6c32c72 with merge 05872da...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/131)
Approved by: jmcadden
Pushing 05872da9bf00183d50fce47bd9727d4998d28590 to master...

**Pull request closed without merging**
