### PR TITLE
 feat(Messenger): Hosted queues messages

### PR DESCRIPTION
**Pull request by jmcadden**
feat(PoolAllocator): Pass list of cpuid to allocate

### CODE REVIEW

**Comment by BetsyRT** [comment]
:umbrella: The latest upstream changes (presumably cd49b31) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by jmcadden** [comment]
@BetsyRT try

**Comment by BetsyRT** [comment]
:hourglass: Trying commit 74ab951 with merge cb38b10...

**Comment by BetsyRT** [comment]
:broken_heart: Test failed - [runtests](http://192.168.73.2:8010/builders/runtests/builds/202)

**Comment by jmcadden** [comment]
@BetsyRT retry

**Comment by jmcadden** [comment]
@BetsyRT try

**Comment by BetsyRT** [comment]
:hourglass: Trying commit 6f9b9bf with merge 34c5e1f...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/204)
State: approved= try=True

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 6f9b9bf has been approved by `jmcadden`

**Comment by jmcadden** [comment]
@BetsyRT +r

**Pull request merged**
