### PR TITLE
[merged] refactor(docker/kvm-qmu): separate boot scripts

### PR DESCRIPTION
**Pull request by jmcadden**
Divides the scripts that run inside the container into `start.sh`
that configures the host machine, and `spawn.sh` that configures and
boots the VM.

### CODE REVIEW

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit a2f8d04 has been approved by `jmcadden`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit a2f8d04 with merge 7a61919...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/182)
Approved by: jmcadden
Pushing 7a6191983f56569d48859edf78c72dc704b50d01 to master...

**Pull request closed without merging**
