### PR TITLE
fix(EbbRef): Add missing include headers

### PR DESCRIPTION
**Pull request by jmcadden**

### CODE REVIEW

**Comment by jmcadden** [comment]
r+

**Comment by jmcadden** [comment]
+r

**Comment by BetsyRT** [comment]
:pushpin: Commit c7534cd has been approved by `jmcadden`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit c7534cd with merge 8a04752...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/21)
Approved by=jmcadden
Pushing 8a0475203ac5fee7936b21314103c3d035b6befe to master...

**Pull request merged**
