### PR TITLE
fix(Gthread): Block on recursive mutex lock

### PR DESCRIPTION
**Pull request by jmcadden**

### CODE REVIEW

**Comment by jmcadden** [comment]
@BetsyRT try

**Comment by BetsyRT** [comment]
:hourglass: Trying commit a094615 with merge a0709c4...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/157)
State: approved= try=True

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit a094615 has been approved by `jmcadden`

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:bulb: This pull request was already approved, no need to approve it again.

**Comment by BetsyRT** [comment]
:pushpin: Commit a094615 has been approved by `jmcadden`

**Pull request merged**
