### PR TITLE
[merged] feat(VMemAllocator): add range reserve function

### PR DESCRIPTION
**Pull request by jmcadden**

### CODE REVIEW

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit a5202ee has been approved by `jmcadden`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit a5202ee with merge 899179d...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://10.241.31.7:8010/builders/runtests/builds/9)
Approved by: jmcadden
Pushing 899179d3c8a0580a85d7cf3765698de7619a48df to master...

**Pull request closed without merging**
