### PR TITLE
fix(hosted): Bump boost coroutine version

### PR DESCRIPTION
**Pull request by dschatzberg**
A change to the boost coroutine library forced us to conditionally
modify some of our code. This also applies to Boost 1.55.

### CODE REVIEW

**Comment by jmcadden** [comment]
Is this required for foreseeable changes to the code, or just a nice-to-have?

**Comment by dschatzberg** [comment]
This is a bug fix. Without this change, boost 1.55 won't work

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 089fb70 has been approved by `jmcadden`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 089fb70 with merge 079056d...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/84)
Approved by=jmcadden
Pushing 079056dea6182f4373e951ed4ad707b7885aaa4c to master...

**Pull request merged**
