### PR TITLE
chore(all): remove deprecated apps and build files

### PR DESCRIPTION
**Pull request by jmcadden**
Deletes files dependant on and part of the 'old' build system

### CODE REVIEW

**Comment by dschatzberg** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 5fb6e98 has been approved by `dschatzberg`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 5fb6e98 with merge 1d1a8c0...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/82)
Approved by=dschatzberg
Pushing 1d1a8c02180dae3cfed22aeb511aad93d3087132 to master...

**Pull request merged**
