### PR TITLE
[merged] chore(docker): Update homu and buildbot

### PR DESCRIPTION
**Pull request by dschatzberg**

### CODE REVIEW

**Comment by handong32** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 563158a has been approved by `handong32`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 563158a with merge 53e515c...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/96)
Approved by: handong32
Pushing 53e515c697b78611078121ee328e2a7092b2f786 to master...

**Pull request closed without merging**
