### PR TITLE
chore(all): remove support for libfdt

### PR DESCRIPTION
**Pull request by jmcadden**

### CODE REVIEW

**Comment by dschatzberg** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit bf8ed77 has been approved by `dschatzberg`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit bf8ed77 with merge b9cdbe9...

**Comment by BetsyRT** [comment]
:broken_heart: Test failed - [runtests](http://192.168.73.2:8010/builders/runtests/builds/83)

**Comment by dschatzberg** [comment]
@BetsyRT retry

**Comment by BetsyRT** [comment]
:hourglass: Testing commit bf8ed77 with merge c340c17...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/85)
Approved by=dschatzberg
Pushing c340c17b1e938cb0b6a7b8411642e60ee9f6ee04 to master...

**Pull request merged**
