### PR TITLE
[merged] fix(build): conflict with prev EBBRT_SRCDIR usage

### PR DESCRIPTION
**Pull request by jmcadden**
This fix to the makefile conforms to the original usage of EBBRT_SRCDIR

### CODE REVIEW

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 0cfe261 has been approved by `jmcadden`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 0cfe261 with merge a56e2f2...

**Comment by jmcadden** [comment]
@BetsyRT r-

**Comment by jmcadden** [comment]
@BetsyRT force

**Comment by BetsyRT** [comment]
:bomb: Buildbot returned an error: `Authorization failed`

**Comment by jmcadden** [comment]
@BetsyRT clean

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 0cfe261 has been approved by `jmcadden`

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:bulb: This pull request was already approved, no need to approve it again.

**Comment by BetsyRT** [comment]
:pushpin: Commit 0cfe261 has been approved by `jmcadden`

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 483a749 has been approved by `jmcadden`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 483a749 with merge ca7b500...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/126)
Approved by: jmcadden
Pushing ca7b500523922aa02c6caf7af9db9305b114145e to master...

**Pull request closed without merging**
