### PR TITLE
[merged] fix(Gthread): test recursive mutex

### PR DESCRIPTION
**Pull request by jmcadden**

### CODE REVIEW

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit a696cb6 has been approved by `jmcadden`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit a696cb6 with merge 4a47a18...

**Comment by BetsyRT** [comment]
:boom: Test timed out

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:bulb: This pull request was already approved, no need to approve it again.

- This pull request previously failed. You should add more commits to fix the bug, or use `retry` to trigger a build again.

**Comment by BetsyRT** [comment]
:pushpin: Commit a696cb6 has been approved by `jmcadden`

**Comment by handong32** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:bulb: This pull request was already approved, no need to approve it again.

- This pull request previously failed. You should add more commits to fix the bug, or use `retry` to trigger a build again.

**Comment by BetsyRT** [comment]
:pushpin: Commit a696cb6 has been approved by `handong32`

**Comment by handong32** [comment]
@BetsyRT retry

**Comment by handong32** [comment]
@BetsyRT retry

**Comment by BetsyRT** [comment]
:hourglass: Testing commit a696cb6 with merge 336dd07...

**Comment by handong32** [comment]
@BetsyRT retry

**Comment by BetsyRT** [comment]
:hourglass: Testing commit a696cb6 with merge 33c9aa3...

**Comment by handong32** [comment]
@BetsyRT r-

**Comment by handong32** [comment]
@BetsyRT retry

**Comment by handong32** [comment]
@BetsyRT retry

**Comment by handong32** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit a696cb6 has been approved by `handong32`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit a696cb6 with merge 3f36ae9...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/162)
Approved by: handong32
Pushing 3f36ae986512df6e2cd04b6d00069b05383e0c08 to master...

**Pull request closed without merging**
