### PR TITLE
feat(EbbRef) Centralized and explosed Id to Ref Address calculation

### PR DESCRIPTION
**Pull request by jappavoo**
In order to make it easier to extend the object model I unified
the calculation of a Ref Address from an Id in a method:
uintptr_t ebbrt::IdToRefAddr(const EbbId id)

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: fd306f6ee58a9cbf1c3f72d5fc8d4b7a04481683
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/SESA/EbbRT/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit bedfaad has been approved by `jmcadden`

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:bulb: This pull request was already approved, no need to approve it again.

**Comment by BetsyRT** [comment]
:pushpin: Commit bedfaad has been approved by `jmcadden`

**Comment by jmcadden** [comment]
@BetsyRT try

**Comment by jmcadden** [comment]
@BetsyRT clean

**Comment by jmcadden** [comment]
@BetsyRT try

**Pull request merged**
