### PR TITLE
chore(ci): Ensure use of clang-format 3.8

### PR DESCRIPTION
**Pull request by dschatzberg**
This changes the CI infrastructure to use clang-format 3.8

### CODE REVIEW

**Comment by dschatzberg** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit f6884ba has been approved by `dschatzberg`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit f6884ba with merge 9164668...

**Comment by BetsyRT** [comment]
:broken_heart: Test failed - [runtests](http://192.168.73.2:8010/builders/runtests/builds/26)

**Comment by dschatzberg** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 158c8e0 has been approved by `dschatzberg`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 158c8e0 with merge 365c583...

**Comment by BetsyRT** [comment]
:broken_heart: Test failed - [runtests](http://192.168.73.2:8010/builders/runtests/builds/27)

**Comment by dschatzberg** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 2fde1cb has been approved by `dschatzberg`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 2fde1cb with merge 5a7de62...

**Comment by BetsyRT** [comment]
:broken_heart: Test failed - [runtests](http://192.168.73.2:8010/builders/runtests/builds/28)

**Comment by dschatzberg** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 81fb92a has been approved by `dschatzberg`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 81fb92a with merge f8e4d71...

**Comment by BetsyRT** [comment]
:broken_heart: Test failed - [runtests](http://192.168.73.2:8010/builders/runtests/builds/29)

**Comment by dschatzberg** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 8c9a00d has been approved by `dschatzberg`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 8c9a00d with merge def36ff...

**Comment by BetsyRT** [comment]
:broken_heart: Test failed - [runtests](http://192.168.73.2:8010/builders/runtests/builds/30)

**Comment by dschatzberg** [comment]
@BetsyRT retry

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 8c9a00d with merge 539c6f1...

**Comment by BetsyRT** [comment]
:broken_heart: Test failed - [runtests](http://192.168.73.2:8010/builders/runtests/builds/31)

**Comment by dschatzberg** [comment]
@BetsyRT retry

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 8c9a00d with merge f021221...

**Comment by BetsyRT** [comment]
:broken_heart: Test failed - [runtests](http://192.168.73.2:8010/builders/runtests/builds/32)

**Comment by dschatzberg** [comment]
@BetsyRT retry

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 8c9a00d with merge 8b929f6...

**Comment by BetsyRT** [comment]
:broken_heart: Test failed - [runtests](http://192.168.73.2:8010/builders/runtests/builds/33)

**Comment by dschatzberg** [comment]
@BetsyRT retry

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 8c9a00d with merge a65f653...

**Comment by BetsyRT** [comment]
:broken_heart: Test failed - [runtests](http://192.168.73.2:8010/builders/runtests/builds/34)

**Comment by dschatzberg** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit b1140ba has been approved by `dschatzberg`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit b1140ba with merge f02e585...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/35)
Approved by=dschatzberg
Pushing f02e585b17c7cee12f23ff5999029a8c7025fef9 to master...

**Pull request merged**
