### PR TITLE
[merged] Add CmdlineArgs library

### PR DESCRIPTION
**Pull request by dschatzberg**

### CODE REVIEW

**Comment by handong32** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit e1fce3a has been approved by `handong32`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit e1fce3a with merge e75756c...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/95)
Approved by: handong32
Pushing e75756c52ac9a47395cdd1123b0bfb9b4e493ab1 to master...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/95)
Approved by: handong32
Pushing e75756c52ac9a47395cdd1123b0bfb9b4e493ab1 to master...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/95)
Approved by: handong32
Pushing e75756c52ac9a47395cdd1123b0bfb9b4e493ab1 to master...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/95)
Approved by: handong32
Pushing e75756c52ac9a47395cdd1123b0bfb9b4e493ab1 to master...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/95)
Approved by: handong32
Pushing e75756c52ac9a47395cdd1123b0bfb9b4e493ab1 to master...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/95)
Approved by: handong32
Pushing e75756c52ac9a47395cdd1123b0bfb9b4e493ab1 to master...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/95)
Approved by: handong32
Pushing e75756c52ac9a47395cdd1123b0bfb9b4e493ab1 to master...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/95)
Approved by: handong32
Pushing e75756c52ac9a47395cdd1123b0bfb9b4e493ab1 to master...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/95)
Approved by: handong32
Pushing e75756c52ac9a47395cdd1123b0bfb9b4e493ab1 to master...

**Pull request closed without merging**
