### PR TITLE
Add application generation script to contrib

### PR DESCRIPTION
**Pull request by jmcadden**
Script will generate a simple "hello world" hosted+native EbbRT application

### CODE REVIEW

**Comment by jmcadden** [comment]
@BetsyRT try

**Comment by BetsyRT** [comment]
:hourglass: Trying commit ba9c134 with merge f701737...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/179)
State: approved= try=True

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit ba9c134 has been approved by `jmcadden`

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:bulb: This pull request was already approved, no need to approve it again.

**Comment by BetsyRT** [comment]
:pushpin: Commit ba9c134 has been approved by `jmcadden`

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:bulb: This pull request was already approved, no need to approve it again.

**Comment by BetsyRT** [comment]
:pushpin: Commit ba9c134 has been approved by `jmcadden`

**Comment by jmcadden** [comment]
@BetsyRT try

**Comment by BetsyRT** [comment]
:hourglass: Trying commit 5b37e59 with merge 08ba26a...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://192.168.73.2:8010/builders/runtests/builds/180)
State: approved= try=True

**Pull request merged**
