### PR TITLE
[merged] Refactor(VMemAllocator): Force print on page fault

### PR DESCRIPTION
**Pull request by jmcadden**
simple change

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 3937fab98c2e94c30960b74134c682cacc7a28f8
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/SESA/EbbRT/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by jmcadden** [comment]
@BetsyRT try

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:pushpin: Commit 79d7bc1 has been approved by `jmcadden`

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 79d7bc1 with merge 9bbe799...

**Comment by jmcadden** [comment]
|

**Comment by jmcadden** [comment]
@BetsyRT r+

**Comment by BetsyRT** [comment]
:bulb: This pull request was already approved, no need to approve it again.

- This pull request is currently being tested. If there's no response from the continuous integration service, you may use `retry` to trigger a build again.

**Comment by BetsyRT** [comment]
:pushpin: Commit 79d7bc1 has been approved by `jmcadden`

**Comment by jmcadden** [comment]
@BetsyRT try

**Comment by jmcadden** [comment]
@BetsyRT retry

**Comment by BetsyRT** [comment]
:hourglass: Trying commit 79d7bc1 with merge f61d0d8...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://10.241.31.7:8010/builders/runtests/builds/6)
State: approved=jmcadden try=True

**Comment by BetsyRT** [comment]
:hourglass: Testing commit 79d7bc1 with merge 57f4f31...

**Comment by BetsyRT** [comment]
:sunny: Test successful - [runtests](http://10.241.31.7:8010/builders/runtests/builds/7)
Approved by: jmcadden
Pushing 57f4f313e30f78947e0843b0b58ff6fb1bdfcb15 to master...

**Pull request closed without merging**
